### ISSUE TITLE
altac - Error: failed to open directory

### ISSUE THREAD

**Issue by Ezneh** [alta-lang/alta#13]
Hi, I am trying to transcompile the example from the getting started guide but I always get the same error:

"Error: failed to open directory"

So here is anything that might be relevant:
1. altac is installed in /usr/local/bin/
2. alta-runtime and alta-stdlib are placed in the /usr/local/include
3. I am on Debian 9, using the root user account.
4. command line: altac hello.alta

Any help / hint on anything I missed or did wrong ? Should the alta-runtime and alta-stdlib be placed elsewhere ?

**Comment by facekapow** [comment]
1) Well yes, `alta-runtime` and `alta-stdlib` should be placed in `/usr/local/lib`
2) The change above will make it transpile, but to compile the C code as an executable, copy the following to a file called `package.alta.yaml` and run `altac -c hello.alta`. The resulting executable should be in `./alta-build/_build/bin/hello`.

```yaml
name: hello
version: 1.0.0
targets:
- name: hello
  main: hello.alta
  type: exe
```

I'm very sorry about the lack of proper documentation (I will certainly update the Getting Started guide with this information), I kind of rushed to get word out about the project. Thank you for taking the time to test it out!

**Comment by Ezneh** [comment]
Alright, it's working now. Thanks a lot.

I also tested on Windows and didn't get any error (beside the fact that I needed to also add the package.alta.yaml and that the lib folders needed to be on the PATH).

So, on the getting started guide, there are 2 things that need to be precised:
1. adding the lib folders in the PATH
2. adding a package.alta.yaml file
